name = "Dog"
canter = false
shove = false
pass = false
leap = true
pull = false
focus = false
crit_boost = false
battle_canter = false
ferry = false
zone_of_control = false
armored = false
flying = false
agile = false

[bases]
hp = 20
power = 6
defense = 8
resistance = 0
dexterity = 4
movement = 5
constitution = 5
reflexes = 3

[growths]
hp = 100
power = 40
defense = 60
resistance = 20
dexterity = 40
movement = 0
constitution = 0
reflexes = 0
