name = "Luvui"

[class]
identifier = ""

[bases]
hp = 0
power = 0
defense = 0
resistance = 0
dexterity = 0
movement = 0
constitution = 0
reflexes = 0

[growths]
hp = 0
power = 0
defense = 0
resistance = 0
dexterity = 0
movement = 0
constitution = 0
reflexes = 0
